# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'http://gitlab.pab.com.cn/ARCH/share/CocoaPods/Specs.git'
target 'PodTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for PodTestProject
  pod 'YYKit'
  pod 'ABD'

  target 'PodTestProjectUITests' do
    # Pods for testing
  end

end
